import time
import sys


while 1:
    
    sys.stdout.write("L2:0")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L2:0")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L2:0")
    sys.stdout.flush()
    time.sleep(6)
    sys.stdout.write("L2:1")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L2:1")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L2:1")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L2:0")
    sys.stdout.flush()
    time.sleep(0.01)

    sys.stdout.write("L1:0")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L1:0")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L1:0")
    sys.stdout.flush()
    time.sleep(7)
    sys.stdout.write("L1:1")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L1:1")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L1:1")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L1:0")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L1:0")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L1:0")
    sys.stdout.flush()
    time.sleep(0.01)

    sys.stdout.write("L3:0")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L3:0")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L3:0")
    sys.stdout.flush()
    time.sleep(7)
    sys.stdout.write("L3:1")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L3:1")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L3:1")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L3:0")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L3:0")
    sys.stdout.flush()
    time.sleep(0.01)
    sys.stdout.write("L3:0")
    sys.stdout.flush()
    time.sleep(0.01)
    
